"""repo access, pending invites, org settings

Revision ID: 11fd28c9beaa
Revises: a6629ec80490
Create Date: 2026-07-18 19:08:37.569718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fd28c9beaa'
down_revision = 'a6629ec80490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_invite_org_email')
    )
    with op.batch_alter_table('org_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_invites_organization_id'), ['organization_id'], unique=False)

    op.create_table('repo_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_push', sa.Boolean(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'user_id', name='uq_repo_access_repo_user')
    )
    with op.batch_alter_table('repo_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_access_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_access_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
       batch_op.add_column(sa.Column('default_scan_frequency', sa.String(length=16), nullable=False, server_default='off'))
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restricted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_column('restricted')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('default_scan_frequency')

    with op.batch_alter_table('repo_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_repo_access_repo_id'))

    op.drop_table('repo_access')
    with op.batch_alter_table('org_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_invites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_org_invites_email'))

    op.drop_table('org_invites')
    # ### end Alembic commands ###
