"""add gmail_connections table

Revision ID: a36ca2d10046
Revises: 74d6a0e25f54
Create Date: 2026-07-26 14:16:33.295203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36ca2d10046'
down_revision = '74d6a0e25f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gmail_address', sa.String(length=255), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gmail_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_connections_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_connections_user_id'))

    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
