"""add slack_connections, sbom_path

Revision ID: a451c9347c13
Revises: a36ca2d10046
Create Date: 2026-07-27 02:51:19.306241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a451c9347c13'
down_revision = 'a36ca2d10046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_webhook_url', sa.Text(), nullable=False),
    sa.Column('channel_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_connections_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sbom_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('sbom_path')

    with op.batch_alter_table('slack_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_connections_user_id'))

    op.drop_table('slack_connections')
    # ### end Alembic commands ###
